# このワークフローを実行するには
# GitHubリポジトリとAWS環境との接続が確立している必要がある
name: cdk diff
on: workflow_call

permissions:
  contents: read
  id-token: write
  pull-requests: write

env:
  ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ID }}:role/${{ secrets.ROLE_NAME }}
  SESSION_NAME: gh-oidc-${{ github.run_id }}-${{ github.run_attempt }}
  AWS_REGION: ap-northeast-1

jobs:
  cdk-diff:
    runs-on: ubuntu-latest

    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          role-session-name: ${{ env.SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run `cdk diff`
        run: |
          npm install
          echo '# cdk diffの結果' > cdk-diff-result.txt
          npx cdk diff >> cdk-diff-result.txt

      - name: Post a comment
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const fs = require('fs')
            const result = fs.readFileSync('cdk-diff-result.txt', 'utf8')
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: result
            })
